version: '3.3'
services:
  server:
    build: server
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_DATABASE: salesassistentdb
      MYSQL_USER: chatlynuser
      MYSQL_PASSWORD: chatlynpass
      MYSQL_HOSTNAME: maria_db
    links:
      - maria_db
    depends_on:
      - maria_db
    # Host mount path overwrite for nodemon - only for DEV!
    command: nodemon server.js openai.js
    volumes:
      # :Z may needs to be removed, if this does not work
      - ./server:/usr/src/app:Z
  maria_db:
    # Use of a modified datbase in 'db'-folder.
    # See README.md for more information.
    build: db
    restart: always
    environment:
      MYSQL_DATABASE: salesassistentdb
      MYSQL_USER: chatlynuser
      MYSQL_PASSWORD: chatlynpass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: chatlynpassroot
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: maria_db
  # angular: # The name of the service
  #   container_name: angular  # Container name
  #   build: 
  #     context: angular
  #     dockerfile: Dockerfile
  #   ports: 
  #     - '80:80' # Port mapping
  #   volumes:
  #     - ./angular:/src/usr/app